[ssdtank/appdata]
    use_template = sink

[ssdtank/vmstore]
    use_template = sink
    recursive = yes

[template_sink]
    frequently = 0
    hourly = 4
    daily = 30
    monthly = 3
    yearly = 0
    autosnap = no
    autoprune = yes
